# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/runWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_runWidget(object):
    def setupUi(self, runWidget):
        runWidget.setObjectName("runWidget")
        runWidget.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(runWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.dataLayout = QtWidgets.QHBoxLayout()
        self.dataLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.dataLayout.setObjectName("dataLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.scrollImages = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.scrollImages.sizePolicy().hasHeightForWidth())
        self.scrollImages.setSizePolicy(sizePolicy)
        self.scrollImages.setWidgetResizable(True)
        self.scrollImages.setObjectName("scrollImages")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 170, 415))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.listImages = QtWidgets.QListView(self.scrollAreaWidgetContents_2)
        self.listImages.setGeometry(QtCore.QRect(0, 0, 172, 421))
        self.listImages.setObjectName("listImages")
        self.scrollImages.setWidget(self.scrollAreaWidgetContents_2)
        self.leftLayout.addWidget(self.scrollImages)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.leftLayout.addWidget(self.progressBar)
        self.leftLayout.setStretch(0, 1)
        self.leftLayout.setStretch(1, 5)
        self.dataLayout.addLayout(self.leftLayout)
        self.centralLayout = QtWidgets.QVBoxLayout()
        self.centralLayout.setObjectName("centralLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralLayout.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRun = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonRun.setObjectName("buttonRun")
        self.horizontalLayout.addWidget(self.buttonRun)
        self.buttonStop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonStop.setObjectName("buttonStop")
        self.horizontalLayout.addWidget(self.buttonStop)
        self.centralLayout.addLayout(self.horizontalLayout)
        self.centralLayout.setStretch(0, 5)
        self.centralLayout.setStretch(1, 1)
        self.dataLayout.addLayout(self.centralLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.scrollResults = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollResults.setWidgetResizable(True)
        self.scrollResults.setObjectName("scrollResults")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 170, 446))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.tableSettings = QtWidgets.QTableView(self.scrollAreaWidgetContents_3)
        self.tableSettings.setGeometry(QtCore.QRect(0, 0, 172, 451))
        self.tableSettings.setObjectName("tableSettings")
        self.scrollResults.setWidget(self.scrollAreaWidgetContents_3)
        self.rightLayout.addWidget(self.scrollResults)
        self.dataLayout.addLayout(self.rightLayout)
        self.dataLayout.setStretch(0, 2)
        self.dataLayout.setStretch(1, 5)
        self.dataLayout.setStretch(2, 2)
        self.mainLayout.addLayout(self.dataLayout)
        self.logLayout = QtWidgets.QHBoxLayout()
        self.logLayout.setObjectName("logLayout")
        self.editLog = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.editLog.setObjectName("editLog")
        self.logLayout.addWidget(self.editLog)
        self.mainLayout.addLayout(self.logLayout)
        self.mainLayout.setStretch(0, 3)
        self.mainLayout.setStretch(1, 1)

        self.retranslateUi(runWidget)
        QtCore.QMetaObject.connectSlotsByName(runWidget)
        runWidget.setTabOrder(self.editLog, self.buttonRun)
        runWidget.setTabOrder(self.buttonRun, self.buttonStop)

    def retranslateUi(self, runWidget):
        _translate = QtCore.QCoreApplication.translate
        runWidget.setWindowTitle(_translate("runWidget", "Form"))
        self.buttonRun.setText(_translate("runWidget", "Run"))
        self.buttonStop.setText(_translate("runWidget", "Stop"))

