from readerWriter.file_reader import load_file
from readerWriter.data_refiner import refine_data
from evaluators.compute_flicker import calculate_flicker_amplitude,flicker_amplitude_to_frequency
from evaluators.compute_nu_max import compute_nu_max